// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package onefeed_th_sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type News struct {
	ID          int64            `json:"id"`
	Title       string           `json:"title"`
	Link        string           `json:"link"`
	Source      string           `json:"source"`
	ImageUrl    pgtype.Text      `json:"image_url"`
	PublishDate pgtype.Timestamp `json:"publish_date"`
	FetchedAt   pgtype.Timestamp `json:"fetched_at"`
}

type NewsTag struct {
	NewsID int64 `json:"news_id"`
	TagID  int32 `json:"tag_id"`
}

type Source struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Tags      pgtype.Text      `json:"tags"`
	RssUrl    pgtype.Text      `json:"rss_url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Tag struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
