// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: news.sql

package onefeed_th_sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BulkInsertNewsParams struct {
	Title       string           `json:"title"`
	Link        string           `json:"link"`
	Source      string           `json:"source"`
	ImageUrl    pgtype.Text      `json:"image_url"`
	PublishDate pgtype.Timestamp `json:"publish_date"`
}
